### ISSUE TITLE
screenshots are all unavailable anymore.

### ISSUE THREAD

**Issue by Ka-lip** [TRIAEIOU/Flexible-cloze#2]
Hi guys,

The screenshots are all unavailable anymore.
Do you have any backup screenshots?

I saw this addon before and start to try it now but without screenshots it makes me difficult to get started.

Thank you.
@TRIAEIOU

**Comment by triaeiou** [comment]
I inserted a couple of screenshots demonstrating the general idea of function, however I think you may be looking for some other type of screenshot? What exactly are you wondering about? Also, please consider using the support thread on ankiweb (https://forums.ankiweb.net/t/flexible-cloze-support-thread/14504) for use questions.

**Comment by Ka-lip** [comment]
Hi @TRIAEIOU , 
thanks for the reply.
I mean the pictures in this page are not available.
https://ankiweb.net/shared/info/1632356464

I have checked the link you offered. Thank you.
